// Copyright 2023 LandscapeCombinator. All Rights Reserved.

#pragma once

#include "BuildingFromSpline/BuildingConfiguration.h"

#include "Components/SplineComponent.h"
#include "Components/SplineMeshComponent.h"
#include "Components/DynamicMeshComponent.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "SegmentTypes.h"

#include "Building.generated.h"

#define LOCTEXT_NAMESPACE "FBuildingFromSplineModule"

using namespace UE::Geometry;

UCLASS(meta = (PrioritizeCategories = "Building"))
class BUILDINGFROMSPLINE_API ABuilding : public AActor
{
	GENERATED_BODY()

public:
	ABuilding();

	virtual void Destroyed() override;
	
	double MinHeightLocal = MAX_dbl;
	double MaxHeightLocal = MAX_dbl;
	double MinHeightWorld = MAX_dbl;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Building")
	TObjectPtr<USceneComponent> EmptySceneComponent;
	
	UPROPERTY(
		VisibleAnywhere, BlueprintReadWrite, Category = "Building",
		meta = (DisplayPriority = "3")
	)
	TObjectPtr<USplineComponent> SplineComponent;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TObjectPtr<UStaticMeshComponent> StaticMeshComponent;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TObjectPtr<UDynamicMeshComponent> DynamicMeshComponent;

	UPROPERTY(
		EditAnywhere, BlueprintReadWrite, Category = "Building",
		meta = (DisplayPriority = "3")
	)
	TObjectPtr<UBuildingConfiguration> BuildingConfiguration;

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "101")
	)
	void DeleteBuilding();

#if WITH_EDITOR

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "100")
	)
	void GenerateBuilding();

	UFUNCTION(BlueprintCallable, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void ConvertToStaticMesh();

	UFUNCTION(BlueprintCallable, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void ConvertToVolume();
	
	UFUNCTION(BlueprintCallable, Category = "Building")
	void GenerateStaticMesh();

	UFUNCTION(BlueprintCallable, Category = "Building")
	void GenerateVolume();
	
	UFUNCTION(BlueprintCallable, Category = "Building")
	void AppendBuilding(UDynamicMesh* TargetMesh);

	void ComputeMinMaxHeight();

	UFUNCTION()
	void SetReceivesDecals();

protected:

	virtual void PostEditChangeProperty(FPropertyChangedEvent &PropertyChangedEvent) override;

#endif

private:
	int GetFloorMaterialID() { return 0; }
	int GetCeilingMaterialID() { return 1; }
	int GetExteriorMaterialID()
	{ 
		if (IsValid(BuildingConfiguration) && BuildingConfiguration->BuildingGeometry == EBuildingGeometry::BuildingWithFloorsAndEmptyInside)
		{
			return 2;
		}
		else
		{
			return 0;
		}
	}
	int GetInteriorMaterialID() { return 3; }
	int GetRoofMaterialID()
	{ 
		if (IsValid(BuildingConfiguration) && BuildingConfiguration->BuildingGeometry == EBuildingGeometry::BuildingWithFloorsAndEmptyInside)
		{
			return 4;
		}
		else
		{
			return 1;
		}
	}
	
	UPROPERTY()
	bool bIsGenerating = false;
	
	/* Holds a pointer to the volume generated by this actor. We destroy the volume when generating a new one. */
	UPROPERTY(DuplicateTransient)
	AVolume* Volume = nullptr;
	
	UPROPERTY(VisibleAnywhere, DuplicateTransient, Category = "Building")
	TArray<TObjectPtr<USplineMeshComponent>> SplineMeshComponents;
	
	UPROPERTY(VisibleAnywhere, DuplicateTransient, Category = "Building")
	TArray<TObjectPtr<UInstancedStaticMeshComponent>> InstancedStaticMeshComponents;

	UPROPERTY(DuplicateTransient)
	FString StaticMeshPath;

	// same as SplineComponent, but all points have the same Z coordinate as the lowest point,
	// and there are subdivisions (depending on the WallSubdivions property of the BuildingConfiguration)
	// and the points are clockwise (when seen from above in Unreal, which isn't the same as clockwise in TPolygon2
	// because of inverted Y-axis)
	TObjectPtr<USplineComponent> BaseClockwiseSplineComponent;
	TArray<FTransform> BaseClockwiseFrames;
	TArray<double> BaseClockwiseFramesTimes;
	TArray<FVector2D> BaseVertices2D;
	TArray<FVector2D> InternalWallPolygon;
	TArray<FVector2D> ExternalWallPolygon;
	TArray<int> IndexToInternalIndex;
	TMap<UStaticMesh*, UInstancedStaticMeshComponent*> MeshToISM;

#if WITH_EDITOR

	FVector2D GetIntersection(FVector2D Point1, FVector2D Direction1, FVector2D Point2, FVector2D Direction2);
	void DeflateFrames(TArray<FTransform> Frames, TArray<FVector2D>& OutOffsetPolygon, TArray<int>& OutIndexToOffsetIndex, double Offset);

	TArray<int> SplineIndexToBaseSplineIndex;
	void ComputeBaseVertices();
	void ComputeOffsetPolygons();
	TArray<FVector2D> MakePolygon(bool bInternalWall, double BeginDistance, double Length);
	FVector2D GetShiftedPoint(TArray<FTransform> Frames, int Index, double Shift, bool bIsLoop);
	void ComputeWindowsPositionsParameterizedByDistance(FWindowsSpecification &WindowsSpecification);
	TArray<float> GetSafeWindowsPositions(const TArray<float> &WindowsPositions, float WindowsWidth);

	void AppendWallsWithHoles(
		UDynamicMesh* TargetMesh, bool bInternalWall, double WallHeight,
		double HolesWidth, double HolesHeight, double HoleDistanceToFloor, double ZOffset,
		const TArray<float> &HolesPositions,
		int MaterialID
	);
	void AppendWallsWithHoles(
		UDynamicMesh* TargetMesh, bool bInternalWall, double WallHeight, double ZOffset,
		FWindowsSpecification &WindowsSpecification, int MaterialID
	);
	void AppendWallsWithHoles(UDynamicMesh* TargetMesh);
	void AddSplineMesh(UStaticMesh* StaticMesh, double BeginDistance, double Length, double Height, double ZOffset);
	void AppendAlongSpline(UDynamicMesh* TargetMesh, bool bInternalWall, double BeginDistance, double Length, double Height, double ZOffset, int MaterialID);
	void AppendRoof(UDynamicMesh* TargetMesh);
	bool AppendFloors(UDynamicMesh *TargetMesh);
	void AppendBuildingStructure(UDynamicMesh* TargetMesh);
	bool AppendBuildingWithoutInside(UDynamicMesh *TargetMesh);
	
	void AddWindowsMeshes();
	void AddWindowsMeshes(FWindowsSpecification &WindowsSpecification, int i);

#endif
	void DestroySplineMeshComponents();
	void DestroyInstancedStaticMeshComponents();

};

#undef LOCTEXT_NAMESPACE