// Copyright 2023 LandscapeCombinator. All Rights Reserved.

#pragma once

#include "BuildingFromSpline/BuildingConfiguration.h"

#include "Components/SplineComponent.h"
#include "Components/SplineMeshComponent.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "DynamicMeshActor.h"
#include "SegmentTypes.h"

#include "Building.generated.h"

#define LOCTEXT_NAMESPACE "FBuildingFromSplineModule"

using namespace UE::Geometry;

UCLASS(meta = (PrioritizeCategories = "Building"))
class BUILDINGFROMSPLINE_API ABuilding : public ADynamicMeshActor
{
	GENERATED_BODY()

public:
	ABuilding();

	virtual void Destroyed() override;
	
	double MinHeightLocal = MAX_dbl;
	double MaxHeightLocal = MAX_dbl;
	double MinHeightWorld = MAX_dbl;
	
	UPROPERTY(
		VisibleAnywhere, BlueprintReadWrite, Category = "Building",
		meta = (DisplayPriority = "3")
	)
	TObjectPtr<USplineComponent> SplineComponent;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TObjectPtr<UStaticMeshComponent> StaticMeshComponent;

	UPROPERTY(
		EditAnywhere, BlueprintReadWrite, Category = "Building",
		meta = (DisplayPriority = "3")
	)
	TObjectPtr<UBuildingConfiguration> BuildingConfiguration;

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void GenerateBuilding();

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void DeleteBuilding();

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void ConvertToStaticMesh();

	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Building",
		meta = (DisplayPriority = "5")
	)
	void ConvertToVolume();
	
	UFUNCTION(BlueprintCallable, Category = "Building")
	void GenerateStaticMesh();
	UFUNCTION(BlueprintCallable, Category = "Building")
	void GenerateVolume();
	
	UFUNCTION(BlueprintCallable, Category = "Building")
	void AppendBuilding(UDynamicMesh* TargetMesh);

	void ComputeMinMaxHeight();

	UFUNCTION()
	void SetReceivesDecals(bool bReceivesDecal);

protected:

	virtual void PostEditChangeProperty(FPropertyChangedEvent &PropertyChangedEvent) override;


private:
	const int FloorMaterialID = 0;
	const int CeilingMaterialID = 1;
	const int ExteriorMaterialID = 2;
	const int InteriorMaterialID = 3;
	const int RoofMaterialID = 4;

	
	/* Holds a pointer to the volume generated by this actor. We destroy the volume when generating a new one. */
	UPROPERTY()
	AVolume* Volume = nullptr;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TArray<TObjectPtr<USplineMeshComponent>> SplineMeshComponents;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TObjectPtr<UInstancedStaticMeshComponent> InstancedDoorsComponent;
	
	UPROPERTY(VisibleAnywhere, Category = "Building")
	TObjectPtr<UInstancedStaticMeshComponent> InstancedWindowsComponent;

	// same as SplineComponent, but all points have the same Z coordinate as the lowest point,
	// and the points are clockwise (when seen from above in Unreal, which isn't the same as clockwise in TPolygon2
	// because of inverted Y-axis
	TObjectPtr<USplineComponent> BaseClockwiseSplineComponent;
	TArray<FTransform> BaseClockwiseFrames;
	TArray<double> BaseClockwiseFramesTimes;
	TArray<FVector2D> BaseVertices2D;
	TArray<FVector2D> InternalWallPolygon;
	TArray<FVector2D> ExternalWallPolygon;
	TArray<int> IndexToInternalIndex;

	FVector2D GetIntersection(FVector2D Point1, FVector2D Direction1, FVector2D Point2, FVector2D Direction2);
	void DeflateFrames(TArray<FTransform> Frames, TArray<FVector2D>& OutOffsetPolygon, TArray<int>& OutIndexToOffsetIndex, double Offset);

	TArray<int> SplineIndexToBaseSplineIndex;
	void ComputeBaseVertices();
	void ComputeOffsetPolygons();
	TArray<FVector2D> MakePolygon(bool bInternalWall, double BeginDistance, double Length);
	FVector2D GetShiftedPoint(TArray<FTransform> Frames, int Index, double Shift, bool bIsLoop);
	void AppendWallsWithHoles(
		UDynamicMesh* TargetMesh, bool bInternalWall, double WallHeight,
		double MinDistanceHoleToCorner, double MinDistanceHoleToHole, double HolesWidth, double HolesHeight, double HoleDistanceToFloor, double ZOffset,
		bool bBuildWalls,
		TArray<float> &OutHolePositions,
		int MaterialID
	);
	void AppendWallsWithHoles(UDynamicMesh* TargetMesh);
	void AddSplineMesh(UStaticMesh* StaticMesh, double BeginDistance, double Length, double Height, double ZOffset);
	void AppendAlongSpline(UDynamicMesh* TargetMesh, bool bInternalWall, double BeginDistance, double Length, double Height, double ZOffset, int MaterialID);
	void AppendRoof(UDynamicMesh* TargetMesh);
	bool AppendFloors(UDynamicMesh *TargetMesh);
	bool AppendSimpleBuilding(UDynamicMesh *TargetMesh);
	void ClearSplineMeshComponents();
};

#undef LOCTEXT_NAMESPACE